---
application:
  name: "presidentonline"
  project: "presidentonline"
  organization: "QoveryCommunity"
routers:
- name: "main-presidentonline"
  routes:
  - application_name: "presidentonline"
    paths:
    - "/*"
