version: '2'

services:
  presidentonline-web:
    container_name: container-apache-presidentonline
    build :
      context: ./
      dockerfile: www/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      virtualtheque_net:
         ipv4_address: 172.16.0.2
  

networks:
  presidentonline_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24